### ISSUE TITLE
Feature Request - если ownership = владеем исходным кодом - заполнить миссив ссылок на исходники

### ISSUE THREAD

**Issue by SychevIgor** [SEAFTeam/seaf-dzo-core#108]
Если мы владеем исходным кодом системы, то стоит добавить массив ссылок на репы.
https://github.com/SEAFTeam/seaf-dzo-core/blob/4a72b237dc7572b96a9c2100aa6a7d4ad99c4f12/entities/app/components/base.yaml#L18C20-L18C41 я про вот это значение у системы

**Comment by talifan** [comment]
Правило отключено до переделки. https://github.com/SEAFTeam/seaf-dzo-core/pull/113
