### ISSUE TITLE
Bug Report - правило из стандарта TACMN_1-Ч06.01.7-02 не соответствует описанию и требует переимплементации

### ISSUE THREAD

**Issue by SychevIgor** [SEAFTeam/seaf-dzo-core#109]
Правило TACMN_1-Ч06.01.7-02 говорит, что "Наличие механизмов обеспечения непрерывности  в соответствии с классами критичности систем мониторинга:
Business Critical и выше: High Availability, Disaster Recovery
Для остальных: High Availability"

Но правило валидации, вообще не соответствует этому описанию. 
Правило, https://github.com/SEAFTeam/seaf-dzo-core/blob/4a72b237dc7572b96a9c2100aa6a7d4ad99c4f12/entities/ta/rules/p6/06.01.7-02.yaml#L14 лишь валидирует наличие поля cluster_id , которое просто строка https://github.com/SEAFTeam/seaf-dzo-core/blob/4a72b237dc7572b96a9c2100aa6a7d4ad99c4f12/entities/ta/dzo_entities.yaml#L491

наличие поля и хоть какого-то значения в нем- не говорит нам ничего об уровне критичности системы мониторинга. 
Данное правило в текущем виде- не проверяет и не гарантирует ничего и требует корректной имплементации

**Comment by talifan** [comment]
Правило отключено до переделки. https://github.com/SEAFTeam/seaf-dzo-core/pull/113
