### ISSUE TITLE
Feature Request - изменить правила в стандартах для k8s с учетом появления выгрузки из k8s в seaf (в частности TACIR_1-КП-КО-1-01)

### ISSUE THREAD

**Issue by SychevIgor** [SEAFTeam/seaf-dzo-core#112]
Сейчас разрабатывается выгрузка из k8s. в этой выгрузке, ноды- это отдельная сущность, а не свойство самого кластера.
из-за этого, ломается данное TACIR_1-КП-КО-1-01 правило т.к. не может найти заполненное поле количество узлов.
![image](https://github.com/user-attachments/assets/84f5594f-7a99-4b56-8d4a-aabdd5d118f9)

![image](https://github.com/user-attachments/assets/6a9727a7-fa40-40b4-909e-8d170e591ae9)

**Comment by talifan** [comment]
Правило отключено до переделки. https://github.com/SEAFTeam/seaf-dzo-core/pull/113

**Comment by SychevIgor** [comment]
главное не забыть при переделки задачку открыть обратно. для меня статус- закрыть - это поставить статус сделано или не будет сделано. текущее закрытие- ни к одному из вариантов не сводится

**Comment by talifan** [comment]
В данном виде сделано вообще не будет. Будет в другом виде.
