### ISSUE TITLE
смысл закомментированного файла в dzo-core в папке docs

### ISSUE THREAD

**Issue by Scicommunity** [SEAFTeam/seaf-dzo-core#20]
Уточнить назначение закомментированного файла в dzo-core в папке docs 
https://github.com/SEAFTeam/seaf-dzo-core/blob/master/docs/root.yaml
Возможно не удаленный артефакт.

**Comment by talifan** [comment]
Удалено в https://github.com/SEAFTeam/seaf-dzo-core/pull/114
