### ISSUE TITLE
Bug Request - berezka в example из core

### ISSUE THREAD

**Issue by SychevIgor** [SEAFTeam/seaf-dzo-core#23]
https://github.com/SEAFTeam/seaf-dzo-core/blob/c48cc43d647ad5c673e647667b64ac8beb144b74/architecture/app/domains.yaml#L3C12-L3C13

березка наверное все таки должна быть в example, а не в dzo-core

**Comment by kmyachin** [comment]
Добавлю ссылку на ранее заведенный баг https://github.com/SEAFTeam/seaf-dzo-core/issues/21

**Comment by SychevIgor** [comment]
раз уже есть, значит дубль.
