### ISSUE TITLE
Feature Request - вывести реестр объектов BA/Goal

### ISSUE THREAD

**Issue by SychevIgor** [SEAFTeam/seaf-dzo-core#24]
Сущность goals есть, в view с таблицей нет. Надо вывести, иначе не понятно зачем это все вести вообще

**Comment by kmyachin** [comment]
Любой view является специфичным, решающим прикладную задачу. Основная задача фреймворка позволять реализовывать собственным view, подходящие под процессы компании.
В данном направлении в первую очередь стоит расширять пример и обучать использованию фреймворка SEAF.

**Comment by SychevIgor** [comment]
к концепции - вопросов нет, вопрос к реализации. есть сущность для описания есть, но ни где не используется- это называет dead code. при наличии хотя бы вывода табличного- это перестает быть мертвым кодом.
ну и есть разница- между кастомизацией для конкретного dzo и тем, что нужно всем dzo. 

для меня-  это аналог функции substring... могу написать и сам, но от нормального framework я бы это ждал из коробки
