### ISSUE TITLE
Bug Request - класс систему у k8s - мониторинг или логирование

### ISSUE THREAD

**Issue by SychevIgor** [SEAFTeam/seaf-dzo-core#37]
https://github.com/SEAFTeam/seaf-dzo-core/blob/c48cc43d647ad5c673e647667b64ac8beb144b74/entities/ta/dzo_entities.yaml#L40

кажется, что из не понятно источника приходит словарь классов. Мне не понятно- что означает класс системы мониторинг-логирования для k8s . k8s может обслуживать любые системы ведь.

похожую ошибку с классификаторами уже где-то фиксили, но кажется- что просканировать все и разобраться

**Comment by talifan** [comment]
Изменил в https://github.com/SEAFTeam/seaf-dzo-core/pull/49

**Comment by SychevIgor** [comment]
@talifan я бы переоткрыл т.к. ровно та же проблема есть еще много где https://github.com/SEAFTeam/seaf-dzo-core/blob/v1.2.9/entities/ta/dzo_entities.yaml и у DC, и у сети и т.п.

**Comment by talifan** [comment]
Игорь, я уточнил там классы в сущностях ещё раз. В целом, данные классы созданы для обеспечения обратной совместимости с КА ДЗО в будущем. По сути, нам они не нужны в модели, но были добавлены для формирования отчётности. https://github.com/SEAFTeam/seaf-dzo-core/pull/65
