### ISSUE TITLE
Необходимость ссылка на сервера в containers k8s

### ISSUE THREAD

**Issue by SychevIgor** [SEAFTeam/seaf-dzo-core#38]
Сейчас, в сущности container - есть ссылка на массив серверов.
Во первых, кажется такая детализация в KA - излишняя, это физических уровень и уровень deployment runtime, а мы в КА все таки runtime процессы не описываем

с другой стороны, в стандарте cloud native есть пункт- что прибивание контейнеров к серверам- это антипаттерн.

**Comment by talifan** [comment]
Игорь, привет.
Т.к. некоторые ДЗО запускают контейнеры прям на серверах эта связь пока останется. Если будущем заметим, что не используется - уберём.
