### ISSUE TITLE
Feature Request - в k8s pod дописать в title полю PV - что это про persistant volume, а не про platform v

### ISSUE THREAD

**Issue by SychevIgor** [SEAFTeam/seaf-dzo-core#39]
Может и мелочь, но первое время - казалось, что вопрос не про хранилище снижу, а про продукт. если расшифровать PV - все будет просто.
не все архитекторы знатоки k8s, но platform v продукты в дзо слышали все.

**Comment by talifan** [comment]
https://github.com/SEAFTeam/seaf-dzo-core/pull/48
