### ISSUE TITLE
Bug Report - K8S POD - количество экземплярах в КА

### ISSUE THREAD

**Issue by SychevIgor** [SEAFTeam/seaf-dzo-core#40]
Кажется, что количество экземпляров pOD - должен знать deployment, а не сам обьект POD.
Кроме того, при использовании auto-scale - количество реплик в KA-  достаточно бесполезное поле т.к. он варьируется в runtime.

**Comment by talifan** [comment]
Изменено в https://github.com/SEAFTeam/seaf-dzo-core/pull/50
