### ISSUE TITLE
Feature Request - раз есть deployment k8s, то стоит добавить еще statefull/statelessset т.к. pod может быть не связан с deploement

### ISSUE THREAD

**Issue by SychevIgor** [SEAFTeam/seaf-dzo-core#41]
Feature Request - раз есть deployment k8s, то стоит добавить еще statefull/statelessset т.к. pod может быть не связан с deploement

**Comment by talifan** [comment]
Исправленое в https://github.com/SEAFTeam/seaf-dzo-core/pull/54
