### ISSUE TITLE
Убрать ссылку на k8s из k8s pod т.к. ссылка есть в deployment?

### ISSUE THREAD

**Issue by SychevIgor** [SEAFTeam/seaf-dzo-core#42]
я не понимаю, зачем в seaf, который Корпоративную Архитектуру представляет, ссылка из pod на k8s, если есть цепочка из pod->deployment-k8s. да и сама это связь - это уровень runtime deployment архитектуры. Описывать такое- мало полезно т.к. оно из reverse видно должно быть

Кажется, что мы усложняем ссылочную структуру (создаем такую реляционную модель) не добавляя ничего поверх нее (валидаторов или визуализаторов)

**Comment by talifan** [comment]
Изменил в https://github.com/SEAFTeam/seaf-dzo-core/pull/51
