### ISSUE TITLE
Bug Report - на метамодели не отображаются связи k8s cluster с сетями, серверами и az (возможно потому, что это массивы)

### ISSUE THREAD

**Issue by SychevIgor** [SEAFTeam/seaf-dzo-core#43]
Выглядит как ошибка т.к. из метамодели хочется понять связи между сущностями, а сейчас часть из них не отображается даже на общей метамодели. 
Если связь есть, пусть и через массив- как пользователь, я ожидаю увидеть связь на схеме

![image](https://github.com/SEAFTeam/seaf-dzo-core/assets/578954/cc15022e-0eb5-4978-bf97-4d1721b6b232)

**Comment by koa73** [comment]
ок

**Comment by SychevIgor** [comment]
аналогичная проблема с сетями в enterprise. прямо было больно пытаться общаться с сетевиками нашими, глядя на эту модель.

**Comment by koa73** [comment]
Ошибку исправят в ближайшем релизе  
Исправить руками можно в файле stalker.yaml
![stalker_yaml](https://github.com/SEAFTeam/seaf-dzo-core/assets/8171271/b4fc2e57-7f3a-4b6f-9ed1-481b0235f062)

Добавить "хищный" поиск в строку : $scan_props($merge([$deep.**.properties, $deep.**.patternProperties]));

**Comment by talifan** [comment]
Исправление в мастере https://github.com/SEAFTeam/mm-discovery/commit/9ac9915e624146fcdfd5e79da5d72af631b7376c
