### ISSUE TITLE
BA - parties из core превращаются в clients в core-dzo . Кажется- это oversimplification 

### ISSUE THREAD

**Issue by SychevIgor** [SEAFTeam/seaf-dzo-core#47]
Идея parties из core пакета - это любая группа логическая. в core-dzo - это строго клиент судя по полям (kadzo).
Со стороны, выглядит -как очень сильное сужение скоупа для parties entity. 
Может лучше ввести сущность расширение с другим именем/title, чем просто сводить parties к client?

![image](https://github.com/SEAFTeam/seaf-dzo-core/assets/578954/f96b156a-a995-4033-8496-680e6b937b97)

**Comment by SychevIgor** [comment]
в том-же example - там смешиваются и клиенты и внутренние организации... а значит не только clients

**Comment by SychevIgor** [comment]
кстати - не понятно, почему в sample не отображается Сосенки и content_matter_buz
это баг или фича? 
![image](https://github.com/SEAFTeam/seaf-dzo-core/assets/578954/0a96637e-f15c-4b4f-82b9-725ba8a7f426)

**Comment by SychevIgor** [comment]
При этом, сущностей channel из kadzo- в seaf нет. и получается что 1 в 1 конвертировать из kadzo  в seaf не получается и не понятно- какая картина целевая

**Comment by kmyachin** [comment]
См. как описываются json-схемы. seaf-dzo расширяет сущности из базовой модели дополнительными аттрибутами. Аттрибуты являются необязательными, то есть не все сущности обязаны их иметь

**Comment by SychevIgor** [comment]
Технически - я понимаю, что расширение. но это странное расширение, которое сужение на самом деле. 
Нужна отдельная сущность клиент, наследующая поля от parties.

**Comment by kmyachin** [comment]
Что ты имеешь ввиду под "сужением" ?
