### ISSUE TITLE
Feature Request - импорт валидаторов из kadzo

### ISSUE THREAD

**Issue by SychevIgor** [SEAFTeam/seaf-dzo-core#60]
В kadzo были очень полезные валидаторы, которые помогали нам исправлять не точность в описании и задавали уровень требований много к чему.

Было бы замечательно, если бы эти валидаторы были импортированы (добавлены в roadmap) из kadzo в seaf.
Это бы помогло нам проверять свое соответствие лучшим практикам и здравому смыслу- не только раз в год во время сдачи отчетности, но и в процессе ведение регулярной архитектурной деятельности.

**Comment by kmyachin** [comment]
Валидаторы КА ДЗО не планируется переносить в SEAF. Это отдельная модель, которая в будущем сможет жить рядом с seaf-dzo-core. При этом "нативная" миграция позволит применять проверки к результату миграции. Более того, мы стремимся реализовать миграцию таким образом, чтобы часть объекта можно было описать в одной модели, а другую часть (при желании) в другой.

**Comment by SychevIgor** [comment]
Возможно- мы про разное.
Для меня важны валидаторы change types, статусы жизненного цикла и т.п. заполненность обязательных полей. они были в kadzo, а в seaf- это все не работает. при этом - это не kadzo специфичные вещи, это то- что относится к базовой валидации любой модели.

**Comment by SychevIgor** [comment]
Что такое "При этом "нативная" миграция позволит применять проверки к результату миграции" (C)? 
Я бы хотел, разрабатывать корп архитектуру на базе seaf, чтобы уже в seaf применялись все базовые валидаторы и уже затем делать экспорт в kadzo и чтобы валидаторы kadzo были функционально идентичны.

Сейчас когда в seaf нет валидаторов- при теоретическом экспорте в kadzo - я уже в kadzo ловить ошибки валидации и заполнения данных, затем буду идти в seaf, вносить правки там и повторять выгрузку. Если бы в seaf были валидаторы, то этот лишний цикл- можно было бы не делать.

Понятно, что сейчас я делаю наоборот- выгружаю из kadzo в seaf, но это не целевой способ.

**Comment by kmyachin** [comment]
Все верно.
В условном будущем у тебя будут 2 папки с метамоделями _metamodel_/seaf-dzo-core (+seaf-core) и _metamodel_/kadzo.
Данные ты сможешь заполнять в сущностях seaf-dzo-core и при этом увидишь ошибки, которые выдаст метамодель kadzo применительно к соответствующим объектам модели seaf-dzo-core.

**Comment by SychevIgor** [comment]
ну что-же, будем ждать появления этого пакета kadzo доступного. т.к. метамодели seaf/kadzo во многом не совместимы- я так понимаю kadzo будет очень сильно перепилен, иначе одни и те же валидаторы явно не смогут отработать

**Comment by kmyachin** [comment]
Будет доработан seaf-dzo-core
