### ISSUE TITLE
Bug Report - класс системы явно лишний у многих сервисов ТА

### ISSUE THREAD

**Issue by SychevIgor** [SEAFTeam/seaf-dzo-core#64]
Тот-же баг, что и тут https://github.com/SEAFTeam/seaf-dzo-core/issues/37 но для других обьектов

и у DC https://github.com/SEAFTeam/seaf-dzo-core/blob/9e7359f18abbb15ea827472eea13151e501f6c84/entities/ta/dzo_entities.yaml#L922
и у сети
https://github.com/SEAFTeam/seaf-dzo-core/blob/9e7359f18abbb15ea827472eea13151e501f6c84/entities/ta/dzo_entities.yaml#L559
и у кластера https://github.com/SEAFTeam/seaf-dzo-core/blob/9e7359f18abbb15ea827472eea13151e501f6c84/entities/ta/dzo_entities.yaml#L622
compute service https://github.com/SEAFTeam/seaf-dzo-core/blob/9e7359f18abbb15ea827472eea13151e501f6c84/entities/ta/dzo_entities.yaml#L686
и у бекапа https://github.com/SEAFTeam/seaf-dzo-core/blob/9e7359f18abbb15ea827472eea13151e501f6c84/entities/ta/dzo_entities.yaml#L745
и у виртуализации https://github.com/SEAFTeam/seaf-dzo-core/blob/9e7359f18abbb15ea827472eea13151e501f6c84/entities/ta/dzo_entities.yaml#L804
и у стораджа https://github.com/SEAFTeam/seaf-dzo-core/blob/9e7359f18abbb15ea827472eea13151e501f6c84/entities/ta/dzo_entities.yaml#L863

и у зоны доступности https://github.com/SEAFTeam/seaf-dzo-core/blob/9e7359f18abbb15ea827472eea13151e501f6c84/entities/ta/dzo_entities.yaml#L981

**Comment by talifan** [comment]
Создано для обратной совместимости с КА ДЗО.

**Comment by SychevIgor** [comment]
круто. теперь будем костыли таскать
