### ISSUE TITLE
выпущена версия 1.2.4 без изменения версии в файле dochub.yaml 1.2.2

### ISSUE THREAD

**Issue by SychevIgor** [SEAFTeam/seaf-dzo-core#7]
давайте будем править версию в dochub.yaml при выкатке релиза

![image](https://github.com/SEAFTeam/seaf-dzo-core/assets/578954/10333376-73cf-4e1f-b502-c394a9dfd264)
![image](https://github.com/SEAFTeam/seaf-dzo-core/assets/578954/1cb1ecd2-ed27-4e2a-a9fe-aabda66a9a8e)

**Comment by kmyachin** [comment]
Учтем в следующих релизах.
