### ISSUE TITLE
Feature Request - добавить в widget service(systems/ac/фп) набор интеграций

### ISSUE THREAD

**Issue by SychevIgor** [SEAFTeam/seaf-dzo-core#79]
В kadzo - была полезная карточка АС-ФП. в ней были интеграции, дата обьекты (для которых эта система - мастер система).
Пожалуйста, добавьте в widget аналогичные секции, чтобы seaf был не хуже kadzo

**Comment by kmyachin** [comment]
В seaf карточка прикладного сервиса/компонента строится на виджетах. Механизм виджетов позволяет гибко добавлять нужные элементы под конкретные потребности самим пользователям. И при этом не добавлять "из коробки" те, которые окажутся кому-то не нужными.

**Comment by SychevIgor** [comment]
> В seaf карточка прикладного сервиса/компонента строится на виджетах. Механизм виджетов позволяет гибко добавлять нужные элементы под конкретные потребности самим пользователям. И при этом не добавлять "из коробки" те, которые окажутся кому-то не нужными.

А может проведем опрос - без интеграций - очень печально все это выглядит.
