### ISSUE TITLE
Feature Request - разбить widget dzo_summary.md для АС-систем на части, чтобы не было длинной портянке

### ISSUE THREAD

**Issue by SychevIgor** [SEAFTeam/seaf-dzo-core#80]
в kadzo, были секции Модель владения и Жизненный цикл, которые логично группировали поля.
в seaf- это все одной секции и читабельность- сильно ниже. получается просто длинный список полей, искать в котором тяжелее чем в нескольких секциях

**Comment by kmyachin** [comment]
Виджеты можно расширять самостоятельно под потребности. В том числе можно переопределять/убирать не нужные.
