### ISSUE TITLE
Bug Report TACMN_1-Ч06.05.1-01 - рекомендация и описание правила не соответствуют 

### ISSUE THREAD

**Issue by SychevIgor** [SEAFTeam/seaf-dzo-core#87]
description: >
        Прямой доступ к хранилищу данных мониторинга минуя средства визуализации и/или документированный разработчиком СМ API запрещен.
      correction: >
        Внедрить решение Privileged Access Management для доступа к СМ.

При наличии PAM, если я буду ходить к хранилищу данных- все будет типа ок, с точки зрения правила.
Если я буду без PAM ходить в веб морду графаны или к ее документированному API- правило нарушено. 

Нужно привести рекомендацию и описание к общему знаменателю. 
Если для этого - надо исправить стандарт, хочется, чтобы и стандарт был исправлен. в текущем виде- правило вызывает вопросы.

**Comment by talifan** [comment]
Игорь, в алгоритме проверке проверяется наличие и подключение к РАМ системе. Но уточнить следует стандарт, безусловно. Пока останется как есть.

**Comment by SychevIgor** [comment]
печально, что описание и проверка не дружат
